### ISSUE TITLE
Threats in aionwallet.exe 

### ISSUE THREAD

**Issue by IgoresVer** [aionnetwork/Desktop-Wallet#166]
Blocked by Windows Defender https://www.virustotal.com/ru/file/a618e7778fb0c7aadcbdc0d99348d6f4a74e18e953e8d11c161bbe317123f589/analysis/
after that in new log file "A fatal error has been detected by the Java Runtime Environment:"

**Comment by qoire** [comment]
Should be resolved by correct signing with an EV certificate. Please let us know if this is still occurring for you.
