### ISSUE TITLE
Receive - Account address field is editable

### ISSUE THREAD

**Issue by AionMiner** [aionnetwork/Desktop-Wallet#168]
The account address field is editable on the receive tab, any changes are persistent until restart or lock timeout. Whilst unlikely, if a user mistakenly edits this field and then manually copies the edited address they would be giving senders an invalid receiving address. Note, the 'Copy to clipboard' button does not inherit any changes (nor does the QR code) instead returning the original unedited address.

**Comment by centrys-cristian-ilca** [comment]
Fixed
Changes will be visible in the next release
