### ISSUE TITLE
Error installing Windows wallet

### ISSUE THREAD

**Issue by markgukov** [aionnetwork/Desktop-Wallet#171]
The error is happening at the very end of the installation process, when it says "Installing depencencies..."

> Unable to execute file:
> C:\Users\Mark\AppData\Local\Temp\is-FBNJO.tmp\java.exe
> 
> CreateProcess failed; code 193.
> %1 is not a valid Win32 application.

I'm running Windows 10 64bit.

**Comment by qoire** [comment]
We've updated the installers for v1.1.0. Try re-downloading and installing.
