### ISSUE TITLE
Can't open wallet on MacOS

### ISSUE THREAD

**Issue by erik-iglikov** [aionnetwork/Desktop-Wallet#175]
Mac .dmg application isn't openning at all on MacOS Mojave 10.14.
First time you run it, application jumps for some time in the tray, show message about installation being from unverified third-party from GitHub, we click open, the app icon in tray then dissapear.
Next time we try to open it, it doesn't do anything.

Things that we've tried:
- reinstall app
- delete app and `./aion` folder and reinstall app
- go to `Security and Privacy` and set app installation from App Store and third parties

**Comment by mohnjatthews** [comment]
Things we could try:

1. Open the wallet via the terminal by running `open /Applications/AionWallet.app`.
1. Create a completely new account and install the wallet in there.
1. Validate the `.dmg` by downloading the [`.sha1` file](https://github.com/aionnetwork/Desktop-Wallet/releases/download/1.1.0/AionWallet.dmg.sha1) and running `sha1sum -c ~/Downloads/AionWallet.dmg.sha1`.
1. Open the Mac in **Safe Mode**:
     - Reboot the mac
     - Hold down the `shift key` when you see the Apple Logo
1. Double check that Java is installed correctly by running `java --version` from a terminal.

During any attempt it might be an idea to monitor the log by running `tail -f ~/.aion/log` from a terminal.

**Comment by AionMiner** [comment]
I'm running the wallet without issues on Mojave 10.14

AionWallet.dmg `4b7095895916c86082d982332e70ce60dd2935ae`

Additionally no Java JDK was _installed_ (`jre-10.0.2.jre` is within `~./aion`)

`java --version` returns `No Java runtime present, requesting install.`

Out of curiosity I deleted the wallet app and folders, installed Java SDK 11.0.1+13-LTS and reinstalled the app. Launched without issues.

However jre-10.0.2 is again extracted to `~./aion`

I see in launcher grep is specific: 

```
if [ ! -f ${JAVA_CMD} ] || [ $(${JAVA_CMD} -version 2>&1 | grep "10.0.2" | wc -l) -lt 1 ]
 then
  mkdir -p ${JAVA_INSTALL}
   tar -xzf jre-10.0.2.tar.gz -C ${STORAGE_DIR}
fi
```

Now, if I remove the jre-10.0.2 folder from `~./aion` and edit the launcher file to just:
```
#!/bin/bash -il

open -a AionWallet
```
Assuming this would utilize Java 11.0.1, I get the bouncy Aion icon in tray then **exit**.

Console logs Error:
`spooky magic for /Applications/AionWallet.app/Contents/MacOS/AionWalletLauncher (622F2123)`

```
/System/Library/PrivateFrameworks/TCC.framework/Versions/A/Resources/tccd

Subsystem: com.apple.TCC Category: access
```

**Comment by qoire** [comment]
Update on this:

We found the main issue (atleast for this case) to be that the lack of a pre-existing npm installation would cause the installer to fail. https://github.com/aionnetwork/Desktop-Wallet/pull/184 describes the fix. @centrys-otniel @centrys-cristian-ilca, can we test this on a mac environment in the same circumstances (clean, no software installs of any kind), to verify.

**Comment by centrys-otniel** [comment]
Hi @qoire we included a portable npm in the install kit. However it is archived and if the extraction fails, that will probably cause the issue to fail. I'll test on Monday

**Comment by centrys-otniel** [comment]
Follow-up -  it looks like the issue is most likely the compatibility of the portable `node` or in some extreme case, there is no `tar` utility to unpack the node archive

**Comment by qoire** [comment]
This _should_ be no longer an issue since ``node`` is no longer packaged as part of the our distribution
