### ISSUE TITLE
WIN10: Wallet self-deletes after single use

### ISSUE THREAD

**Issue by backengineer** [aionnetwork/Desktop-Wallet#178]
Just downloaded AionDesktopWallet for the token swap.   This version seems to want delete itself. 
After a single use, it needs to be fully reinstalled and access reestablished with the seed.  I have to say, this is one of the most annoying bugs I have ever encountered.   Please do not tell me this is done for security purposes.   Any chance we can get this fixed with a maintenance release??

**Comment by mohnjatthews** [comment]
Hi @backengineer. When you say this _version seems to want delete itself_, does the wallet actually get deleted? Are all the files missing or are there any left over?

**Comment by backengineer** [comment]
The wallet contents does not get deleted... the .exe file is deleted, shortly after closing the application.
If there is a Shortcut on the desktop that shortcut now points to a .exe file that no longer exists.
The only solution is a reinstall - so everytime the wallet app is opened and then closed it needs to be reinstalled.  Very weird.

**Comment by mohnjatthews** [comment]
@backengineer That's pretty strange, and obviously super annoying.

Are you running any anti-virus stuff by any chance? Maybe Windows Defender? Because it sounds like something on your PC doesn't trust the Aion Wallet. As far as I know the application itself isn't signed, so you may have to add an exception within your anti-virus software.

**Comment by backengineer** [comment]
@mohnjatthews Running McAfee AV, not Win Defender.   The problem may have resolved after a reboot of the machine...  I did not reboot after reinstall.   It appeared as if the .exe file was not autodeleted when reinstalled after a fresh boot.  The machine is at home - I can confirm tonight.

**Comment by mohnjatthews** [comment]
@backengineer ok cool. Let us know if the reboot completely fixes your issue and I'll put a note in the documentation.

**Comment by mohnjatthews** [comment]
@backengineer this is super weird. I take it McAfee's not showing anything useful?

**Comment by backengineer** [comment]
@mohnjatthews  McAfee LiveSafe is usually well behaved and I have never seen it delete a file.   I have had issues with being unable to install a wallet due to McAfee LiveSafe detecting code fragments that are similar to malware or virus.   The standard mode of operation is refusal to install, not allowing install then deleting only the .exe file.

**Comment by mohnjatthews** [comment]
@backengineer Yeah it's a bit of an odd one. That's the issue with a lot of software in the crypto space at the moment though. Companies like McAfee, AVG, Norton, etc are having a hard time catching up.
