### ISSUE TITLE
Installer script resiliency

### ISSUE THREAD

**Issue by qoire** [aionnetwork/Desktop-Wallet#193]
The following output shows two problems: 
1. `[: /Users/user: binary operator expected`
   * Either a problem with unicode characters
   * Or needs double brackets  `[[`
2. `mkdir: /Users/user: Permission denied`
   * Trying to create a subdirectory in the `Users` directory, which the user called `user` does not have permissions to do (which is a little puzzling)
   * We should have a popup to have the user select an adequate install directory for the `.aion` folder? 
  
```
Last login: Fri Nov  9 11:37:14 on console
macbook:~ user 121010$ rm -rf ~/.aion
macbook:~ user 121010$ /Applications/AionWallet.app/Contents/MacOS/AionWalletLauncher
Located script directory: /Applications/AionWallet.app/Contents/MacOS
/Applications/AionWallet.app/Contents/MacOS/AionWalletLauncher: line 20: [: /Users/user: binary operator expected
Could not find Java Install directory. Creating it now ...
mkdir: /Users/user: Permission denied
Unzipping packaged JRE ...
tar: could not chdir to '/Users/user'

mkdir: /Users/user: Permission denied
/Applications/AionWallet.app/Contents/MacOS/AionWalletLauncher: line 58: ${LOG_DIR}/log: ambiguous redirect
Saving session...
...copying shared history...
...saving history...
...completed.
Deleting expired sessions...7 completed.
macbook:~ user 121010$
```

**Comment by qoire** [comment]
Update:
* Try to extract JRE in Application Container (.app) folder
* Ping user indicating error

**Comment by centrys-otniel** [comment]
After looking a bit at the outputs, I think this has a much simpler explanation - there is a ` ` (space character) in the username of that user. This explains both the `binary operator expected` error since there are too many parameters when evaluating the conditions and the permission denied, since the user isn't allowed to create a folder in `/Users`
