### ISSUE TITLE
Very hard to tell what the values are when sending transactions

### ISSUE THREAD

**Issue by JimVanEeden** [aionnetwork/Desktop-Wallet#202]
Can't read the description/label of the inputs where the default value is already filled it (energy and energy price fields). Also, the energy price was massively confusing to me. 10.000.000.000 default value, what's the unit of that? Apparently that translates to 10 amp, but can't find that anywhere.

Would be greatly appreciated if you could make this form more clear!

**Comment by AionMiner** [comment]
Quite a few improvements to the UX are on the way with https://github.com/aionnetwork/Desktop-Wallet/pull/201, in particular https://github.com/aionnetwork/Desktop-Wallet/pull/201/commits/4e09874649b9af0f156c6c413a285a38e3521324

As for clarification on terminology: https://github.com/aionnetwork/aion/wiki/Aion-Terminology
