### ISSUE TITLE
Aion Wallet showing 0 balance

### ISSUE THREAD

**Issue by tjones0808** [aionnetwork/Desktop-Wallet#240]
Hey guys, what am I mssing?

I am using the Aion Desktop Wallet 1.2.2, I am using the default connection, and I have a 0 balance and can't connect to Peers. Block is sitting at 0/0 undefined.

**Comment by mohnjatthews** [comment]
Hi @tjones0808, I'm assuming you closed this issue because you're no longer facing problems? We did have a temporary issue with the default node the wallet connects to, but that has been fixed now.

**Comment by tjones0808** [comment]
hey yeah, i just let it sit online came back after some time and everything was connected and updated. Thanks!
