### ISSUE TITLE
Desktop-Wallet v1.2.2 cannot connect nodes

### ISSUE THREAD

**Issue by Mankit520** [aionnetwork/Desktop-Wallet#242]
Hello, Win10 wallet v1.2.2 cannot connect nodes. Please help me.
![image](https://user-images.githubusercontent.com/47839587/53139992-4e99a680-35c6-11e9-976b-684601d1dd15.png)

**Comment by opensourcenewbie** [comment]
MacOS wallet v1.2.2 has same problem.  0 peers.

**Comment by mohnjatthews** [comment]
I just did a clean installed on the macOS wallet and was connected to 99 peers automatically. @opensourcenewbie @Mankit520 are you both able to uninstall and reinstall the wallet? Make sure to make a backup of your accounts before you uninstall anything.

**Comment by opensourcenewbie** [comment]
@mohnjatthews  Thanks for your message - I appreciate you taking the time to respond.  The problem I faced was not that it wouldn't ever connect, but that it connected and then disconnected, usually as soon as I unlocked the wallet or tried to send AION.  After 3 days of trying, I have finally managed to get the coins out of the wallet, but I won't be using this wallet again until it proves capable of maintaining a connection for extended periods of time.

**Comment by mohnjatthews** [comment]
No problem @opensourcenewbie. Yeah it can be frustrating to deal with, but I'm glad you were able to get access to your `AION`! Keep an eye out for future releases.

@Mankit520 are you still having issues with your wallet?

**Comment by damianm2007** [comment]
Aion Wallet not working my windows... 
I isntall and run.. Application run and automatically off...
... help?

**Comment by mohnjatthews** [comment]
@damianm2007 Do you have any anti-virus software installed on your PC? That may be blocking the wallet from opening.

**Comment by mohnjatthews** [comment]
> Aion Wallet not working my windows...
> I isntall and run.. Application run and automatically off...
> I have windows 10 64 bit
> ... help?

Can you please make a new issue for your problem @damianm2007. This issue is for wallets that cannot connect to nodes. I'm closing for now.
