### ISSUE TITLE
Can't access my AION wallet

### ISSUE THREAD

**Issue by siphon11** [aionnetwork/Desktop-Wallet#244]
Hello, I had and issue. Malwarebytes quarantined my AION wallet as Trojan.
I released the quarantine but have now difficulties accessing my account and I didn't try for months, a year.
All I have saved when creating this wallet is my backup phrase, my public address and a password.
It seems that I didn't get my private key either.
How to possibly recover my wallet?
Thanks

**Comment by siphon11** [comment]
Thanks.
It worked well until saving the account. It friezed Linux and I had to reboot.
Now when I re-open the wallet, I don't have the "Add Account" choice but the "Unlock" choice instead. Then it do not recognize my 12 backup words. 
I'm stuck!! :(
 
-----Original Message-----

**Comment by mohnjatthews** [comment]
No problem. When the wallet asks for your password, it means the password you entered _along with_ your backup phrase.

<img width="397" alt="screen shot 2019-03-06 at 4 25 34 pm" src="https://user-images.githubusercontent.com/9611008/53914820-7fe58e00-402c-11e9-9a9a-35e6c02a5ae7.png">

Whatever you put into the 2nd field is your password.

**Comment by siphon11** [comment]
Thank you.
Would you be kind enough to mention which file I should download for my Linux Mint machine?
That would be helpful and save me a lot of trouble.
Sorry for being so dumb.
AionWallet.dmg.sha1
AionWalletSetup.exe.sha1
aion_ui.zip.sha1
Source code (zip)
Source code (tar.gz)

**Comment by mohnjatthews** [comment]
So you'll want the `aion_ui-v1.2.2.0329ff5.zip` file. Checkout the docs for how to install it: https://docs.aion.network/docs/install-the-aion-desktop-wallet#section-linux

**Comment by siphon11** [comment]
Done, thank you. 
I succeed to import my wallet with my coins on it just by typing the password, no need for the backup phrase, that on a new computer. I guess it's normal!

**Comment by mohnjatthews** [comment]
Once you've added an account there's no way to remove it. If you really want to you can uninstall and reinstall the wallet again to get rid of the 2nd account, but it won't do you any harm to leave it there.

I'm going to close this issue since you've been able to get your account back :)
